### ISSUE TITLE
Wrong upload measurements

### ISSUE THREAD

**Issue by JPYamamoto** [mithereal/ex_speedtest#1]
I wanted to use this library to monitor my internet service, but when running the test, I get around 600 Mbps of upload.
When running the test using the same server directly on [speedtest.net](speedtest.net/) I get around 4.5 Mbps. The results are consistent with the [speedtest-cli](https://github.com/sivel/speedtest-cli).
Do you know why I could be getting wrong results when using this elixir client?

**Comment by mithereal** [comment]
fixed
